// ═══════════════════════════════════════════════════════════════════════════════
// NFINITY CRM — Google Sheet Lead Sync  (Universal Multi-Tenant Edition v2)
// ─────────────────────────────────────────────────────────────────────────────
// THIS FILE IS IDENTICAL FOR EVERY CLIENT WORKSPACE.
// No client-specific values exist in this code.
// All client-specific configuration lives in Script Properties.
//
// ─── FIRST-TIME SETUP ────────────────────────────────────────────────────────
// 1. In your CRM → Settings → Integrations → Google Sheets → click "Generate Config"
// 2. Copy the Script Properties block it gives you.
// 3. In this Script Editor → Project Settings → Script Properties → add each key:
//
//      TENANT_ID        ← your workspace ID (from CRM)
//      WEBHOOK_SECRET   ← the secret generated by the CRM  (keep private)
//      SHEETS_TO_SYNC   ← comma-separated tab names  e.g. "Performance marketer,Intern leads"
//      WEBHOOK_URL      ← (optional — defaults to the production URL below)
//
// 4. Run  ▶ showCurrentConfig()  to verify your properties are saved correctly.
// 5. Run  ▶ testSync()           to send one batch and confirm the connection.
// 6. Run  ▶ setupTrigger()       only AFTER testSync() succeeds.
//
// ─── SUBSEQUENT CLIENTS ──────────────────────────────────────────────────────
// Copy this file as-is into the new client's spreadsheet, then configure their
// own Script Properties (steps 1-6 above). Zero code changes needed.
// ═══════════════════════════════════════════════════════════════════════════════

// ─── STANDARD FIELD MAP ───────────────────────────────────────────────────────
// Maps exact sheet header → CRM payload key. Covers Meta-generated variants.
// NEVER contains client-specific values — safe to share publicly.
var STANDARD_FIELDS = {
  'id':            'lead_id',    // → externalLeadId (dedup key)
  'full_name':     'name',       // → Lead.name (required)
  'phone_number':  'phone',      // → Lead.phone
  'phone':         'phone',
  'mobile':        'phone',
  'mobile_number': 'phone',
  'email':         'email',      // → Lead.email
  'platform':      'source',     // → Lead.source
  'source':        'source',
};

var SKIP_COLUMNS = ['sent_to_crm'];  // never sent to CRM

// ═══════════════════════════════════════════════════════════════════════════════
// CONFIGURATION  (reads from Script Properties — never from hardcoded vars)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Load all client-specific configuration from Script Properties.
 * Called at the start of every public entry-point function.
 * @returns {{webhookUrl, tenantId, webhookSecret, sheetsToSync, spreadsheetId}}
 */
function getConfig_() {
  var props = PropertiesService.getScriptProperties().getProperties();
  var sheetsRaw = (props['SHEETS_TO_SYNC'] || '').split(',');
  return {
    webhookUrl:    props['WEBHOOK_URL'] || 'https://nfinity-crm.onrender.com/api/gsheet-webhook',
    tenantId:      props['TENANT_ID']      || '',
    webhookSecret: props['WEBHOOK_SECRET'] || '',
    sheetsToSync:  sheetsRaw.map(function(s) { return s.trim(); }).filter(Boolean),
    spreadsheetId: SpreadsheetApp.getActiveSpreadsheet().getId(),
  };
}

/**
 * Validate required config. Logs errors and returns false if anything is missing.
 * @param {Object} config - result of getConfig_()
 * @returns {boolean}
 */
function validateConfig_(config) {
  var ok = true;
  if (!config.tenantId) {
    Logger.log('ERROR: Script Property "TENANT_ID" is not set.');
    Logger.log('       Get it from: CRM → Settings → Integrations → Google Sheets → Generate Config');
    ok = false;
  }
  if (!config.webhookSecret) {
    Logger.log('ERROR: Script Property "WEBHOOK_SECRET" is not set.');
    Logger.log('       Get it from: CRM → Settings → Integrations → Google Sheets → Generate Config');
    ok = false;
  }
  if (!config.sheetsToSync || config.sheetsToSync.length === 0) {
    Logger.log('ERROR: Script Property "SHEETS_TO_SYNC" is not set or empty.');
    Logger.log('       Set it to a comma-separated list of tab names, e.g.: Performance marketer,Intern leads');
    ok = false;
  }
  return ok;
}

// ═══════════════════════════════════════════════════════════════════════════════
// HMAC-SHA256  (identical for all clients — no client-specific values)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Compute HMAC-SHA256 of message using secret.
 * Returns lowercase hex string — matches Node.js:
 *   crypto.createHmac('sha256', secret).update(message).digest('hex')
 */
function computeHmac_(secret, message) {
  var secretBytes  = Utilities.newBlob(secret).getBytes();
  var messageBytes = Utilities.newBlob(message).getBytes();
  var mac = Utilities.computeHmacSha256Signature(messageBytes, secretBytes);
  return mac.map(function(b) {
    return ('0' + (b & 0xff).toString(16)).slice(-2);
  }).join('');
}

// ═══════════════════════════════════════════════════════════════════════════════
// PAYLOAD BUILDER
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Build a CRM lead payload object from one data row.
 * Standard fields → top-level keys; everything else → customFields.
 *
 * @param {string[]} headers    Lowercased header values
 * @param {string[]} rawHeaders Original (casing-preserved) header values
 * @param {any[]}    row        Data row values
 * @param {number}   rowIndex   0-based index (for fallback lead_id)
 * @param {string}   sheetName  Source tab name (stored as Lead.sheetName)
 * @returns {Object|null}       Payload object, or null if row is invalid
 */
function buildLeadPayload_(headers, rawHeaders, row, rowIndex, sheetName) {
  var iLeadId = headers.indexOf('id');
  var iName   = headers.indexOf('full_name');

  var nameVal = (iName !== -1) ? String(row[iName] || '').trim() : '';
  if (!nameVal) return null;  // name is required

  var leadId = (iLeadId !== -1 && row[iLeadId] && String(row[iLeadId]).trim() !== '')
    ? String(row[iLeadId]).trim()
    : 'GS-' + Date.now() + '-' + rowIndex;

  var payload = {
    lead_id:      leadId,
    name:         nameVal,
    phone:        '',
    email:        '',
    source:       '',
    sheetName:    sheetName || '',
    customFields: {},
  };

  for (var c = 0; c < rawHeaders.length; c++) {
    var rawHeader = rawHeaders[c];
    var header    = headers[c];
    if (!rawHeader || rawHeader === '') continue;
    if (SKIP_COLUMNS.indexOf(header) !== -1) continue;

    var cellValue = row[c];
    if (cellValue instanceof Date) {
      cellValue = cellValue.toISOString();
    } else if (cellValue !== null && cellValue !== undefined) {
      cellValue = String(cellValue);
    } else {
      cellValue = '';
    }

    if (STANDARD_FIELDS[rawHeader]) {
      var payloadKey = STANDARD_FIELDS[rawHeader];
      if (payloadKey !== 'lead_id' && payloadKey !== 'name') {
        payload[payloadKey] = cellValue;
      }
    } else {
      if (cellValue !== '') {
        payload.customFields[rawHeader] = cellValue;
      }
    }
  }

  return payload;
}

// ═══════════════════════════════════════════════════════════════════════════════
// WEBHOOK POST  (signs with HMAC, sends x-spreadsheet-id for binding validation)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Sign and POST a batch of lead payloads to the webhook URL.
 * Sends x-gsheet-signature (HMAC) and x-spreadsheet-id (binding) headers.
 *
 * @param {Object[]} payloads      Array of lead payload objects
 * @param {string}   url           Full webhook URL including query params
 * @param {string}   secret        Plaintext webhook secret from Script Properties
 * @param {string}   spreadsheetId Google Sheets file ID (for server binding validation)
 * @returns {Object|null}          Parsed JSON response, or null on failure
 */
function postToWebhook_(payloads, url, secret, spreadsheetId) {
  var body      = JSON.stringify(payloads);
  var signature = computeHmac_(secret, body);

  var options = {
    method:             'post',
    contentType:        'application/json',
    payload:            body,
    headers: {
      'x-gsheet-signature': signature,
      'x-spreadsheet-id':   spreadsheetId || '',
    },
    muteHttpExceptions: true,
  };

  var response;
  try {
    response = UrlFetchApp.fetch(url, options);
  } catch (fetchErr) {
    Logger.log('ERROR: Network request failed: ' + fetchErr.message);
    return null;
  }

  var statusCode = response.getResponseCode();
  var rawText    = response.getContentText();

  var result;
  try {
    result = JSON.parse(rawText);
  } catch (e) {
    Logger.log('ERROR: Could not parse server response. HTTP ' + statusCode + ' — ' + rawText);
    return null;
  }

  if (result.success !== true) {
    Logger.log('ERROR: CRM rejected the request. HTTP ' + statusCode + '. Message: ' + (result.message || rawText));
    Logger.log('INFO: No rows will be marked. They will be retried on next sync.');
    return null;
  }

  return result;
}

// ═══════════════════════════════════════════════════════════════════════════════
// SYNC — single tab
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Sync one sheet tab: collect unsent rows, POST to CRM, mark sent_to_crm.
 * Marking rules:
 *   errors === 0  → mark all rows TRUE  (created + duplicates both qualify)
 *   errors  > 0  → mark nothing; retry on next sync (CRM dedup prevents doubles)
 */
function syncTab_(ss, tabName, config) {
  var sheet = ss.getSheetByName(tabName);
  if (!sheet) {
    Logger.log('[' + tabName + '] WARNING: Tab not found — skipping.');
    return;
  }

  var lastRow = sheet.getLastRow();
  if (lastRow < 2) {
    Logger.log('[' + tabName + '] INFO: No data rows found.');
    return;
  }

  var data       = sheet.getRange(1, 1, lastRow, sheet.getLastColumn()).getValues();
  var rawHeaders = data[0].map(function(h) { return String(h).trim(); });
  var headers    = rawHeaders.map(function(h) { return h.toLowerCase(); });

  // Auto-add sent_to_crm column if missing
  var iSent = headers.indexOf('sent_to_crm');
  if (iSent === -1) {
    var newCol = sheet.getLastColumn() + 1;
    sheet.getRange(1, newCol).setValue('sent_to_crm');
    Logger.log('[' + tabName + '] INFO: Added "sent_to_crm" column at column ' + newCol + '.');
    data       = sheet.getRange(1, 1, lastRow, sheet.getLastColumn()).getValues();
    rawHeaders = data[0].map(function(h) { return String(h).trim(); });
    headers    = rawHeaders.map(function(h) { return h.toLowerCase(); });
    iSent      = headers.indexOf('sent_to_crm');
  }

  if (headers.indexOf('id') === -1) {
    Logger.log('[' + tabName + '] ERROR: Required column "id" not found. Found: ' + rawHeaders.join(', '));
    return;
  }
  if (headers.indexOf('full_name') === -1) {
    Logger.log('[' + tabName + '] ERROR: Required column "full_name" not found. Found: ' + rawHeaders.join(', '));
    return;
  }

  var toSend     = [];
  var rowIndices = [];

  for (var i = 1; i < data.length; i++) {
    var sentVal = data[i][iSent];
    if (sentVal === true || String(sentVal).toUpperCase() === 'TRUE') continue;

    var payload = buildLeadPayload_(headers, rawHeaders, data[i], i, tabName);
    if (!payload) continue;

    toSend.push(payload);
    rowIndices.push(i + 1);  // 1-based sheet row
  }

  if (toSend.length === 0) {
    Logger.log('[' + tabName + '] INFO: No unsent rows. Nothing to sync.');
    return;
  }

  Logger.log('[' + tabName + '] INFO: Sending ' + toSend.length + ' lead(s) to CRM...');
  var url    = config.webhookUrl + '?workspaceId=' + config.tenantId;
  var result = postToWebhook_(toSend, url, config.webhookSecret, config.spreadsheetId);
  if (!result) return;

  Logger.log(
    '[' + tabName + '] SUCCESS: Created=' + (result.created || 0) +
    ', Duplicates=' + (result.duplicates || 0) +
    ', Errors=' + (result.errors || 0)
  );

  var errors = result.errors || 0;
  if (errors === 0) {
    for (var r = 0; r < rowIndices.length; r++) {
      sheet.getRange(rowIndices[r], iSent + 1).setValue(true);
    }
    Logger.log('[' + tabName + '] INFO: Marked ' + rowIndices.length + ' row(s) as sent_to_crm=TRUE.');
    if ((result.duplicates || 0) > 0) {
      Logger.log('[' + tabName + '] INFO: ' + result.duplicates + ' duplicate(s) skipped by CRM (already exist).');
    }
  } else {
    Logger.log('[' + tabName + '] WARNING: ' + errors + ' row(s) had server-side errors.');
    Logger.log('[' + tabName + '] INFO: No rows marked. All will be retried on next sync.');
    Logger.log('[' + tabName + '] INFO: Previously created rows will be de-duplicated by CRM on retry.');
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// BACKFILL — single tab
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Backfill one tab: sends ALL rows (ignoring sent_to_crm) to the ?update=true endpoint.
 * Backend updates customFields + ad attribution on EXISTING leads only. Never creates new ones.
 * Does NOT modify sent_to_crm. Safe to run multiple times.
 * @returns {{ updated, notFound, errors }} totals for this tab
 */
function backfillTab_(ss, tabName, config) {
  var totals = { updated: 0, notFound: 0, errors: 0 };
  var sheet  = ss.getSheetByName(tabName);

  if (!sheet) {
    Logger.log('[' + tabName + '] WARNING: Tab not found — skipping.');
    return totals;
  }

  var lastRow = sheet.getLastRow();
  if (lastRow < 2) {
    Logger.log('[' + tabName + '] INFO: No data rows found.');
    return totals;
  }

  var data       = sheet.getRange(1, 1, lastRow, sheet.getLastColumn()).getValues();
  var rawHeaders = data[0].map(function(h) { return String(h).trim(); });
  var headers    = rawHeaders.map(function(h) { return h.toLowerCase(); });

  if (headers.indexOf('id') === -1) {
    Logger.log('[' + tabName + '] ERROR: Required column "id" not found.');
    return totals;
  }
  if (headers.indexOf('full_name') === -1) {
    Logger.log('[' + tabName + '] ERROR: Required column "full_name" not found.');
    return totals;
  }

  var toSend = [];
  for (var i = 1; i < data.length; i++) {
    var payload = buildLeadPayload_(headers, rawHeaders, data[i], i, tabName);
    if (payload) toSend.push(payload);
  }

  if (toSend.length === 0) {
    Logger.log('[' + tabName + '] INFO: No valid rows to backfill.');
    return totals;
  }

  Logger.log('[' + tabName + '] INFO: Sending ' + toSend.length + ' row(s) to backfill endpoint...');

  var BATCH_SIZE = 50;
  for (var start = 0; start < toSend.length; start += BATCH_SIZE) {
    var batch  = toSend.slice(start, start + BATCH_SIZE);
    var url    = config.webhookUrl + '?workspaceId=' + config.tenantId + '&update=true';
    var result = postToWebhook_(batch, url, config.webhookSecret, config.spreadsheetId);

    if (result) {
      totals.updated  += result.updated  || 0;
      totals.notFound += result.notFound || 0;
      totals.errors   += result.errors   || 0;
      var batchNum = Math.floor(start / BATCH_SIZE) + 1;
      Logger.log(
        '[' + tabName + '] Batch ' + batchNum + ': ' +
        'Updated=' + (result.updated || 0) + ', ' +
        'NotFound=' + (result.notFound || 0) + ', ' +
        'Errors=' + (result.errors || 0)
      );
    }
  }

  Logger.log(
    '[' + tabName + '] Done — Updated=' + totals.updated +
    ', NotFound=' + totals.notFound + ', Errors=' + totals.errors
  );
  return totals;
}

// ═══════════════════════════════════════════════════════════════════════════════
// PUBLIC ENTRY POINTS  (the functions you call or schedule)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * AUTOMATIC SYNC — called by the 5-minute trigger and by testSync().
 * Reads config from Script Properties. Loops all tabs in SHEETS_TO_SYNC.
 */
function syncNewLeads() {
  var config = getConfig_();
  if (!validateConfig_(config)) return;

  var ss = SpreadsheetApp.getActiveSpreadsheet();
  for (var t = 0; t < config.sheetsToSync.length; t++) {
    Logger.log('[' + config.sheetsToSync[t] + '] Starting sync...');
    syncTab_(ss, config.sheetsToSync[t], config);
  }
}

/**
 * BACKFILL — run ONCE manually after deploying the new backend.
 * Updates customFields + ad attribution on EXISTING leads. Never creates new ones.
 * Loops all tabs in SHEETS_TO_SYNC. Does NOT modify sent_to_crm.
 * Safe to run multiple times (idempotent).
 *
 * ⚠️  Do NOT call this automatically. Run from the Apps Script editor manually.
 */
function backfillAllLeads() {
  Logger.log('=== backfillAllLeads() started ===');
  Logger.log('INFO: Updates customFields/attribution on existing leads. No new leads created.');

  var config = getConfig_();
  if (!validateConfig_(config)) {
    Logger.log('=== backfillAllLeads() ABORTED — fix missing Script Properties ===');
    return;
  }

  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var grandTotal = { updated: 0, notFound: 0, errors: 0 };

  for (var t = 0; t < config.sheetsToSync.length; t++) {
    Logger.log('[' + config.sheetsToSync[t] + '] Starting backfill...');
    var tabTotal = backfillTab_(ss, config.sheetsToSync[t], config);
    grandTotal.updated  += tabTotal.updated;
    grandTotal.notFound += tabTotal.notFound;
    grandTotal.errors   += tabTotal.errors;
  }

  Logger.log('=== backfillAllLeads() complete ===');
  Logger.log(
    'GRAND TOTAL — Updated=' + grandTotal.updated +
    ', NotFound=' + grandTotal.notFound +
    ', Errors=' + grandTotal.errors
  );
  Logger.log('NOTE: sent_to_crm columns were NOT modified. Normal sync is unaffected.');
}

/**
 * STEP 1 — Run this FIRST, BEFORE setupTrigger().
 * Validates your Script Properties and sends one sync cycle.
 * Check Logs (View → Logs) for errors before proceeding to setupTrigger().
 */
function testSync() {
  var config = getConfig_();
  Logger.log('=== testSync() started ===');
  Logger.log('TENANT_ID:       ' + (config.tenantId      || '(NOT SET)'));
  Logger.log('WEBHOOK_URL:     ' + config.webhookUrl);
  Logger.log('WEBHOOK_SECRET:  ' + (config.webhookSecret  ? '(set, ' + config.webhookSecret.length + ' chars)' : '(NOT SET)'));
  Logger.log('SHEETS_TO_SYNC:  ' + (config.sheetsToSync.length ? config.sheetsToSync.join(', ') : '(NOT SET)'));
  Logger.log('SPREADSHEET_ID:  ' + config.spreadsheetId);

  if (!validateConfig_(config)) {
    Logger.log('=== testSync() ABORTED — set missing Script Properties then re-run ===');
    return;
  }
  syncNewLeads();
  Logger.log('=== testSync() finished — check logs above before running setupTrigger() ===');
}

/**
 * STEP 2 — Run AFTER testSync() confirms the connection works.
 * Installs the 5-minute automatic sync trigger.
 * Safe to run multiple times — removes duplicate triggers first.
 *
 * ⚠️  Do NOT run this automatically. Run once from the Apps Script editor.
 */
function setupTrigger() {
  var triggers = ScriptApp.getProjectTriggers();
  for (var i = 0; i < triggers.length; i++) {
    if (triggers[i].getHandlerFunction() === 'syncNewLeads') {
      ScriptApp.deleteTrigger(triggers[i]);
      Logger.log('INFO: Removed existing syncNewLeads trigger.');
    }
  }
  ScriptApp.newTrigger('syncNewLeads')
    .timeBased()
    .everyMinutes(5)
    .create();
  Logger.log('SUCCESS: Trigger created. syncNewLeads will run every 5 minutes automatically.');
}

/**
 * DIAGNOSTIC — prints current Script Properties to the log (non-sensitive view).
 * The actual WEBHOOK_SECRET value is never logged — only its presence/length.
 */
function showCurrentConfig() {
  var config = getConfig_();
  Logger.log('═══════════════════════════════════════');
  Logger.log('  Current Script Configuration');
  Logger.log('═══════════════════════════════════════');
  Logger.log('WEBHOOK_URL:     ' + config.webhookUrl);
  Logger.log('TENANT_ID:       ' + (config.tenantId      || '⚠ NOT SET'));
  Logger.log('WEBHOOK_SECRET:  ' + (config.webhookSecret  ? '✓ set (' + config.webhookSecret.length + ' chars)' : '⚠ NOT SET'));
  Logger.log('SHEETS_TO_SYNC:  ' + (config.sheetsToSync.length ? config.sheetsToSync.join(', ') : '⚠ NOT SET'));
  Logger.log('SPREADSHEET_ID:  ' + config.spreadsheetId);
  Logger.log('═══════════════════════════════════════');
  if (!config.tenantId || !config.webhookSecret || !config.sheetsToSync.length) {
    Logger.log('⚠ Configuration incomplete. Go to CRM → Integrations → Google Sheets → Generate Config');
  } else {
    Logger.log('✓ Configuration looks complete. Run testSync() to verify the connection.');
  }
}
